name: repl
description: A REPL for Dart.
version: 0.1.0+2
homepage: https://www.github.com/maks/dart_repl

environment:
  sdk: ">=2.15.0 <3.0.0"

executables:
  drepl: main

dependencies:
  analyzer: ^3.2.0
  cli_repl: ^0.2.2
  vm_service: ^8.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
